---
- name: Stop kubelete service
  become: true
  systemd:
    state: stopped
    name: etcd

- name: Remove kubelete config
  become: true
  file:
      path: '{{ item }}'
      state: absent
  with_items:
    - '{{ kube_config_dir }}/kubelet.env'