---
- name: load {{ project_name }} vars
  include_vars: 
    file: '{{ kolla_path }}/ansible/roles/{{ project_name }}/defaults/main.yml'

- name: load global path
  include_vars: 
    file: '{{ germ_path }}/germ/openstack/etc/globals.yml'

- name: load germ path
  include_vars: 
    file: '{{ germ_path }}/germ/openstack/etc/germ.yml'

- name: remove resources
  include: remove.yml

- name: deploy resource
  vars:
    action: 'deploy'
    common_run: True
  include_role:
    name: '{{ project_name }}'
