---
project_name: nova

auth_list:
  - 'OS_PROJECT_DOMAIN_NAME=Default'
  - 'OS_USER_DOMAIN_NAME=Default'
  - 'OS_PROJECT_NAME=admin'
  - 'OS_TENANT_NAME=admin'
  - 'OS_USERNAME=admin'
  - 'OS_PASSWORD={{ keystone_admin_password }}'
  - 'OS_AUTH_URL={{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ keystone_admin_port }}/v3'
  - 'OS_INTERFACE=internal'
  - 'OS_IDENTITY_API_VERSION=3'
  - 'OS_REGION_NAME={{ openstack_region_name }}'
  - 'OS_AUTH_PLUGIN=password'
