---
- name: get decrease node neturon agents
  shell: |-
    docker exec \
    {% for var in auth_list %} \
      -e {{ var }} \
    {% endfor %} \
    kolla_toolbox \
    openstack network agent \
    list  --host {{ inventory_hostname }} -f value -c ID
  when: inventory_hostname in groups['decrease']
  delegate_to: '{{ groups["control"] | first }}'
  register: result

- name: delete decrease node neutron agents
  shell: |-
    docker exec \
    {% for var in auth_list %} \
      -e {{ var }}            \
    {% endfor %}              \
    kolla_toolbox             \
    openstack network agent \
    delete {{ item }}
  when: inventory_hostname in groups['decrease']
  delegate_to: '{{ groups["control"] | first }}'
  with_items:
    '{{ result.stdout_lines }}'
