---
- name: clean containers
  include: remove.yml

- set_fact:
    common_run: True

- include_role:
    name: ceph
    tasks_from: start_mons.yml
  when: inventory_hostname in groups['ceph-mon']

- include_role:
    name: ceph
    tasks_from: start_mgrs.yml
  when: inventory_hostname in groups['ceph-mgr']

- include_role:
    name: ceph
    tasks_from: start_rgws.yml
  when: inventory_hostname in groups['ceph-rgw']
