---
- name: Remove Container
  include_role:
    name: 'util/docker/container'
    tasks_from: remove
    apply:
      vars:
        name: '{{ item }}'
  with_items:
    - ceph_rgw
    - ceph_mgr
    - ceph_mon
