---
- name: Remove Container
  include_role:
    name: 'util/docker/container'
    tasks_from: remove
    apply:
      vars:
        name: '{{ project_name }}'

- name: Remove Volume
  include_role:
    name: 'util/docker/volume'
    tasks_from: remove
    apply:
      vars:
        name: '{{ project_name }}'

- name: Ensuring config directories not exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ project_name}}"
    state: absent

