---
- name: Remove Container
  include_role:
    name: 'recover/docker/{{ item }}'
    tasks_from: remove
  vars:
    project_name: 'rabbitmq'
  with_items:
    - 'container'
    - 'volume'

- name: remove config
  vars:
    project_name: rabbitmq
  file:
    path: '{{ node_config_directory }}/{{ project_name }}'
    state: absent
